[package]
name = "baobox-linux"
version = "0.1.0"
edition = "2021"
description = "Baobox Linux 实现：X11 抓屏与截图 CLI"
license = "MIT"

[dependencies]
baobox-app = { path = "../../shared/baobox-app" }
baobox-core = { path = "../../shared/baobox-core" }
baobox-image = { path = "../../shared/baobox-image" }
baobox-render = { path = "../../shared/baobox-render" }
gtk = "0.18"
glib = "0.18"
x11rb = { version = "0.13", features = ["xfixes", "xtest"] }
zbus = { version = "5", default-features = false, features = ["blocking-api", "async-io"] }
aes-gcm = { version = "0.11.0", default-features = false, features = ["aes", "alloc"] }
